<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Naša Kaša Odoslanie',
	'heading' => 'Odoslanie nového formulára',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Začiarknuté',
		'checkbox_unchecked' => 'Nezačiarknuté',
		'submitted_from' => 'Formulár odoslaný z webovej lokality: %s',
		'submitted_by' => 'Adresa IP návštevníka: %s',
		'too_many_submissions' => 'Priveľa nedávnych odoslaní z tejto adresy IP',
		'failed_to_send_email' => 'Nepodarilo sa odoslať e-mail',
		'invalid_reCAPTCHA_private_key' => 'Neplatný súkromný kľúč reCAPTCHA.',
		'invalid_field_type' => 'Neznámy typ poľa „%s“.',
		'unknown_method' => 'Neznáma metóda požiadavky servera'
	),
	'email' => array(
		'from' => 'nasakasa@nasakasa.sk',
		'to' => 'nasakasa@nasakasa.sk'
	),
	'fields' => array(
		'custom_U1597' => array(
			'type' => 'string',
			'label' => 'Názov',
			'required' => true,
			'errors' => array(
				'required' => 'Pole „Názov“ je povinné.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'Pole „E-mail“ je povinné.',
				'format' => 'V poli „E-mail“ je zadaná neplatná e-mailová adresa.'
			)
		),
		'custom_U1592' => array(
			'type' => 'string',
			'label' => 'Správa',
			'required' => true,
			'errors' => array(
				'required' => 'Pole „Správa“ je povinné.'
			)
		),
		'custom_U1629' => array(
			'type' => 'string',
			'label' => 'Spoločnosť',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
